<?php

namespace AppBundle\Repository;

/**
 * FlightModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightModelRepository extends \Doctrine\ORM\EntityRepository
{
}
