<?php

namespace AppBundle\Repository;

/**
 * ReservationModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationModelRepository extends \Doctrine\ORM\EntityRepository
{
}
