<?php

namespace AppBundle\Repository;

/**
 * SiteModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteModelRepository extends \Doctrine\ORM\EntityRepository
{
}
